create database project;
use project;
show tables;
describe customers_medium;
select * from customers_medium;
ALTER TABLE customers_medium
MODIFY signup_date DATE;
select * from menu_items;
ALTER TABLE orders_medium
MODIFY order_time DATETIME,
MODIFY delivery_time DATETIME;
describe orders_medium;



#1. Find the top 5 customers based on their total spending.

select o.customer_id,sum(oi.quantity * oi.price) as total_spending
from orders_medium o inner join order_items oi on o.order_id = oi.order_id
group by o.customer_id order by total_spending desc limit 5;

#2. Find restaurants whose total revenue is greater than 50,000.

select o.restaurant_id,sum(oi.quantity * oi.price) as total_revenue
from orders_medium o inner join order_items oi on o.order_id = oi.order_id
group by o.restaurant_id having total_revenue > 50000 order by total_revenue desc;

#3. Find the total revenue generated by each cuisine.

select r.cuisine,sum(oi.quantity * oi.price) as total_revenue
from restaurants r inner join orders_medium o on r.restaurant_id = o.restaurant_id
inner join order_items oi on o.order_id = oi.order_id
group by r.cuisine order by total_revenue desc;

#4. Find customers who have placed more than 5 orders.

select customer_id,count(order_id) as total_orders
from orders_medium group by customer_id
having total_orders > 5 order by total_orders desc;

#5. Find the restaurants whose rating is higher than the average restaurant rating.

select restaurant_id,cuisine,rating
from restaurants where rating > (select avg(rating) from restaurants)
order by rating desc;

#6. Find the most expensive menu item.

select item_id,restaurant_id,price
from menu_items
where price = (select max(price) from menu_items);

#7. Find restaurants that have received more than 10 delivered orders.

select restaurant_id,count(order_id) as delivered_orders
from orders_medium where status = 'Delivered'
group by restaurant_id having delivered_orders > 10
order by delivered_orders desc;

#8. Find the average order value for every customer.

select o.customer_id,round(avg(oi.quantity * oi.price), 2) as average_order_value
from orders_medium o inner join order_items oi on o.order_id = oi.order_id
group by o.customer_id order by average_order_value desc;

#9. Find customers whose total spending is greater than 10,000.

select o.customer_id,sum(oi.quantity * oi.price) as total_spending
from orders_medium o inner join order_items oi on o.order_id = oi.order_id
group by o.customer_id having total_spending > 10000
order by total_spending desc;

#10. Find the cuisine with the highest average restaurant rating.

select cuisine,round(avg(rating), 2) as average_rating
from restaurants group by cuisine
order by average_rating desc limit 1;

#11. Find all customers who have placed at least one cancelled order.

select distinct customer_id
from orders_medium where status = 'Cancelled';

#12. Find customers who have placed both delivered and cancelled orders.

select customer_id from orders_medium where status = 'Delivered'
and customer_id in (select customer_id from orders_medium where status = 'Cancelled')
group by customer_id;

#13. Find the total number of orders placed in each city.

select c.city,count(o.order_id) as total_orders
from customers_medium c inner join orders_medium o on c.customer_id = o.customer_id
group by c.city order by total_orders desc;

#14. Find cities having more than 100 orders.

select c.city,count(o.order_id) as total_orders
from customers_medium c inner join orders_medium o on c.customer_id = o.customer_id
group by c.city having total_orders > 100 order by total_orders desc;

#15. Display each restaurant’s rating category using case.

select restaurant_id,cuisine,rating,
case when rating >= 4.5 then 'Excellent'
	when rating >= 4 then 'Very Good'
	when rating >= 3 then 'Good'
	else 'Average'
    end as rating_category
from restaurants;

#16. Display customers according to their number of orders.

select customer_id,count(order_id) as total_orders,
case when count(order_id) >= 10 then 'Frequent Customer'
	 when count(order_id) >= 5 then 'Regular Customer'
	 else 'Occasional Customer'
     end as customer_type
from orders_medium group by customer_id;

#17. Find the highest revenue-generating restaurant.

select o.restaurant_id,sum(oi.quantity * oi.price) as total_revenue
from orders_medium o inner join order_items oi on o.order_id = oi.order_id
group by o.restaurant_id order by total_revenue desc limit 1;

#18. Find the cuisine having more than 20 restaurants.

select cuisine,count(restaurant_id) as total_restaurants
from restaurants group by cuisine having total_restaurants > 20 order by total_restaurants desc;
 
#19. Find all orders placed in January.

select * from orders_medium where order_time like '%-01-%';

#20. Find the number of orders placed in each month.

select substr(order_time, 1, 7) as order_month,count(order_id) as total_orders
from orders_medium group by order_month order by order_month;

#21. Find restaurants whose rating is between 4 and 5 and cuisine is either Indian or Chinese.

select * from restaurants where rating between 4 and 5 and cuisine in ('Indian', 'Chinese')
order by rating desc;





